# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-08 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='idGroup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='learn.Gruop'),
            preserve_default=False,
        ),
    ]
