# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_student_idgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='real_name',
        ),
        migrations.AlterField(
            model_name='gruop',
            name='idGroup',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
